### ISSUE TITLE
What's the ETA for an ASP.NET Core 2.2.0 branch

### ISSUE THREAD

**Issue by IvanFarkas** [dotnet-architecture/eShopOnContainers#722] opened 2018-08-26 15:26 UTC
What's the ETA for an **ASP.NET Core 2.2.0** branch?

**Actions**
- Remove the health check code already baked into ASP.NET Core 2.2.0
- Takes full advantage of the new **ASP.NET Core 2.2.0** features
- Add **SignalR C++ client** for **IoT** devices
- Add **IoT** to reference application
- Upgrade to **Bootstrap 4**, **Angular 6**, etc.
- Refactoring

**Comment by deanilvincent** [comment] 2018-08-27 04:38
+1 for this

**Comment by CESARDELATORRE** [comment] 2018-08-27 17:42
As you can see in ASP.NET Core 2.2 roadmap, we won't have its RTM until end of 2018:
https://github.com/aspnet/Announcements/issues/307 

Therefore, in regards eShopOnContainers we won't update code/features related to it until that timeframe, probably one month before RTM we might start working on a new branch about it.

In regards the features we'll take into account I initially think about the following:
- New HealthChecks in ASP.NET Core 2.2
- Minor updates in ASP.NET Core 2.2 in Controllers, etc., sparse code across the solution --> Refactoring
- Upgrade to Bootstrap 4, Angular 6, etc. (This can be done before ASP.NET Core 2.2)

IoT and C++ clients are currently out of the scope of eShopOnContainers.

**Comment by IvanFarkas** [comment] 2018-08-27 20:20
Fair enough. Let me know how I can help you, please.

**Comment by CESARDELATORRE** [comment] 2018-08-27 21:48
Sure! If you can help, you could create two PRs against DEV branch with updates for upgrading to:
- Bootstrap 4
- Angular 6 (For the SPA app)

For other updates like HealthChecks and additional features in ASP.NET Core 2.2 we still need to wait.

**Comment by raboud** [comment] 2018-08-28 00:44
I can handle the SPA changes if no one else wants it...I did it once already. But I also added bootswatch when I did it...I believe.

**Comment by raboud** [comment] 2018-08-29 00:31
@CESARDELATORRE 
this might end up being one PR updating to Angular 6 requires updating @ng-bootstrap/ng-bootstrap which requires updating to Bootstrap 4 and a handful of other minor updates.

I got this all done already...I need to fix an alignment issue caused by Bootstrap 4 then will be ready to check in.

In the mean time I am going to try one more time to do it as 2 PRs.

**Comment by IvanFarkas** [comment] 2018-08-29 13:54
Created **[PR #726](https://github.com/dotnet-architecture/eShopOnContainers/pull/726)** - Updated WebSPA to Angular 6, Bootstrap 4, HttpClient and new rxjs, replaced ng2-toastr with ngx-toastr.

**Comment by raboud** [comment] 2018-08-29 21:47
so a wasted 4 hours for me...yeah

**Comment by mvelosop** [comment] 2019-01-08 13:20
Closing this issue as the 2.2 branch has been merged into dev as of commit b9dcc80acd735842bb1d1cf1007d97d7b1095c97 on JAN-03-2019.

**Closed by mvelosop** 2019-01-08 13:20 UTC
