### ISSUE TITLE
RabbitMQ channel.CallbackException causes blocks and causes deadlock when disposing channel

### ISSUE THREAD

**Issue by david-ernstsson-stratsys** [dotnet-architecture/eShopOnContainers#1052] opened 2019-05-28 17:58 UTC
Hi, after changing to using AsyncEventingBasicConsumer in https://github.com/dotnet-architecture/eShopOnContainers/pull/987 deadlock occurs when unhandled exception

If an unhandled exception occurs in  `EventBusRabbitMQ.Consumer_Received` and channel.CallbackException is invoked then with current implementation `_consumerChannel.Dispose();` blocks and causes deadlock

Thoughts on this? I've failed to find a fix for this and instead choosing to not do anything when `_consumerChannel.IsOpen`

Links with same problem:
https://groups.google.com/forum/#!topic/rabbitmq-users/N76hwS7BEpg
https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/341

**Comment by mvelosop** [comment] 2019-05-28 19:31
Hi @david-ernstsson-stratsys, thanks for the heads up!

What caused the exception?, I'd like to reproduce it to take a closer look.

Thanks.

**Comment by david-ernstsson-stratsys** [comment] 2019-05-29 07:26
@mvelosop 
Manually throwing a new exception instead of say acking the message should do it. There being an exceptioncallback with logic to restore the channel one could presume that would be alright? Behavior then seems to be either a block/deadlock on dispose or it takes some seconds there and instead a block/deadlock on `_connection.CreateModel()` in `DefaultRabbitMQPersistentConnection`

This problem only occurs when using async consumer

**Comment by mvelosop** [comment] 2019-06-17 21:31
Hi @david-ernstsson-stratsys, 

I've been investigating about this "interesting" issue, and even though I couldn't reproduce it, I had found a similar deadlock issue that stopped orders from getting to the final Paid status.

Beginning with one of your suggested links and reading a "bit" I got to a change that seems to have solved my deadlock issue.

Could you try branch [fix/1052-rabbitmq-deadlock ](https://github.com/dotnet-architecture/eShopOnContainers/tree/fix/1052-rabbitmq-deadlock) or at least apply the canges of commit 2621c3695655fa35d7c70a4289cfa5bb4ea06691 to your repo, to check if this works for you too?

Hope this helps.

**Comment by mvelosop** [comment] 2019-06-20 20:45
Although I couldn't reproduce this specific problem, a similar deadlock issue that occurred always during regular processing on the last order status, was solved with PR #1079.

So I'm closing this issue now, but feel free to comment. Will reopen if needed.

**Closed by mvelosop** 2019-06-20 20:45 UTC
