### ISSUE TITLE
Implement resilient connections to Rabbitmq - Issue detected when running on macOS

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet-architecture/eShopOnContainers#157] opened 2017-04-06 05:45 UTC
Having set Docker to 4GB RAM.

When running `docker container ls` I get this.

![image](https://cloud.githubusercontent.com/assets/888718/24739589/fb0b37a4-1a9c-11e7-85ca-dcb1583c4f30.png)

I am missing the Basket API, right?
(According to https://github.com/dotnet/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)#testing-all-the-applications-and-microservices)

**Comment by chlowell** [comment] 2017-04-06 17:10
Yes. If you check the Basket API container's logs, I expect you'll see it exited after failing to connect to rabbitmq. The Basket API can attempt to connect before rabbitmq is ready. We need to create some resiliency here.

**Comment by CESARDELATORRE** [comment] 2017-04-06 18:03
Agreed. It never happened to me when starting the containers, but it could happen.
We need to implement a resilient connection in a similar way we do for EF connections against SQL.
I'm changing the title of this issue so it is clearer to tack it down.

**Comment by CESARDELATORRE** [comment] 2017-04-19 18:03
Yes. This is something that started in the Mac environment (not in Windows) when we added the Event Hub based on a RabbitMQ container. It is caused by the fact that when starting all the containers, in the Mac environment the RabbitMQ container must start not soon enough for the client containers/microservices. For any reason, that is not happening when starting in Docker for Windows.
In any case, this is something we need to fix, we need to make the RabbitMQ connections resilient, so if for any reason it can't connect (when starting or even partial failures in the cloud) we need to implement retry with exponential backoff logic in the client apps.
As a temporal workaround, you could start the RabbitMQ container first (with docker run or a different docker-compose file only for that container) then start the rest of the application with docker-compose (without having the RabbitMQ container in the global docker-compose files).
Please, confirm if that was your issue. We'll reply here when this is fixed.

**Comment by iancooper** [comment] 2017-06-13 21:39
We fix this in Brighter using Polly to run a retry loop in the event we can't reach RMQ. We see the Docker race condition a lot, as it takes time for RMQ to start, even if you explicitly tell on the dependency. I can point you in the direction of our code if you need to see what we are doing, but should be self-evident

**Comment by CESARDELATORRE** [comment] 2017-06-13 21:56
Right. This was aleady fixed a few weeks ago by using Polly's policies. See here:
https://github.com/dotnet-architecture/eShopOnContainers/blob/master/src/BuildingBlocks/EventBus/EventBusRabbitMQ/DefaultRabbitMQPersisterConnection.cs

Ian, if you have any feedback about the code, please tell me. But so far it is working good for us.
I'm closing this issue.

**Closed by CESARDELATORRE** 2017-06-13 21:56 UTC
Labels: bug, Priority 1
