### ISSUE TITLE
CAN'T RUN!

### ISSUE THREAD

**Issue by mohsens22** [dotnet-architecture/eShopOnContainers#397] opened 2017-11-06 15:50 UTC
Hello guys!
I'm having problem for setting things up and running this solution on my machine.
I cloned the repo and tried to run the project, but I failed. Also I done the setup on docker, docker toolkit, npm and other stuff. But when I wanna run the project, I get this shitty error:
![image](https://user-images.githubusercontent.com/22152065/32449683-7e0b361c-c327-11e7-9016-1da82b4abf75.png)
Seems that some useless variables are not set :| . But the point is that they don't seem to be useful in dev env and they prevent me from going through the code. I'm seeing this shit in a couple of machines (Windows 10 RS3 & Windows server 2016)
Any one can help me?

**Comment by CESARDELATORRE** [comment] 2017-11-06 16:54
A few things I'd try:
1. Do you have a similar error when trying to run a hello world ASPNET Core app with Docker?
2. Have you configured additional memory and cores for Docker at Docker settings?
3. Try building the bits locally, with the build-bits script instead the Linux build-bits we
4. Try a second machine with a clean environment, just to isolate if the issue is in the first machine only

________________________________

**Comment by DenisBabarykin** [comment] 2017-11-06 21:08
I had the same problem after upgrading my Visual Studio from 15.3.3 to 15.4.2. Just remove all "*:${TAG:-latest}*" in **docker-compose.yml** and build will go on.

P.S. @CESARDELATORRE, please have a look at Issue #394, I haven't solve this problem yet.

**Comment by CESARDELATORRE** [comment] 2017-11-06 21:58
Oh! That's right. There's a bug in vs2017 15.4x where it is not working when using tags (which is normal)
So, either use VS 2017 15.5 Preview or remove the tags from every docker image name at the docker-compose files.

Right at the begining of the home page and when saying what version of VS to use, we're actually explaining this issue.

**Comment by CESARDELATORRE** [comment] 2017-11-06 23:52
The following is right at the beginning of the home page and the VS 2017 set up page at the Wiki.
Please, confirm if that was your problem:

Note Visual Studio 2017 version required: This is important as of Oct. 11th 2017. For working with Docker and docker-compose files (needed with eShopOnContainers), do not migrate to VS 2017 15.4 as it has a bug when using TAGs in the docker-compose files. Please, either use VS 2017 15.35 or VS 2017 15.5 Preview 1 (bug is fixed here) or later. VS Preview installs next to your stable Visual Studio IDE, allowing you to use either independently. Download of Preview here: https://www.visualstudio.com/vs/preview/

**Comment by CESARDELATORRE** [comment] 2017-11-07 00:47
Closing, as I think it was due to the version of VS 2017 with the bug about Docker tags.
see explanation above.
We can re-open the issue if needed.

**Closed by CESARDELATORRE** 2017-11-07 00:47 UTC

**Comment by mohsens22** [comment] 2017-11-09 22:16
@CESARDELATORRE @DenisBabarykin 
Thanks guys :) The problem was about that VS bug. I removed them and everything is going right.
