### ISSUE TITLE
[Question] Warning CA2007: Do not directly await a Task without calling ConfigureAwait

### ISSUE THREAD

**Issue by eddynaka** [dotnet-architecture/eShopOnContainers#515] opened 2018-02-19 00:05 UTC
Hi,

I have been watching the repository and i got some doubts in how the tasks work in netcore. I have installed the nuget Microsoft.CodeAnalysis.FxCopAnalyzers to see what should appear in the eShopOnContainers solution.

I got almost everywhere the warning CA2007. Should i remove all the async / await, and use only one ConfigureAwait(false) in the first call? What shold be the best implementation for this scenario?

**Comment by rliberoff** [comment] 2018-02-19 11:08
I have exactly the same question!

**Comment by mvelosop** [comment] 2018-06-05 21:22
Closing this issue as could not reproduce it and it's not directly related to an issue with the application.

**Closed by mvelosop** 2018-06-05 21:22 UTC

**Comment by DavidKDeutsch** [comment] 2019-02-27 18:46
FWIW, I am using Microsoft.CodeQuality.Analyzers 2.6.3 (the nuget package, not VSIX), and I get this warning in my .NET Core 2.1 projects

**Comment by JulienBara** [comment] 2019-03-05 14:08
It doesn't seem to be relevant anymore in ASP.NET Core since the way context was working in ASP.NET has changed in ASP.NET Core. The Analyzer is wrong.
Sources:
- https://github.com/JosefPihrt/Roslynator/issues/285
- https://stackoverflow.com/questions/42053135/configureawaitfalse-relevant-in-asp-net-core

Solution:
Consider deactivating this rule of the analyzer.
I personally add `CA2007` in the Project "Property >Build > Suppress Warnings" field from VS

**Comment by mvelosop** [comment] 2019-03-06 12:39
Thanks for the clarification @JulienBara.

I got to understand this a bit better recently.

As I understand now, the ConfigureAwait(false) is recommended for libraries, so that when the awaited task completes, the result is not delivered in the same thread (synchronized) that created the task, because that's costly and it's only needed for UI and ASP.NET (not Core) and hence it should not be a responsibility of a library.

However, .NET Core doesn't have the SyncronizationContext class that was used for that synchronization, so it's basically useless in .NET Core,

ConfigureAwait(false) has a place for **.NET Standard** libraries, because they can be used in .NET Framework applications, where this could be an issue, but definitely it's not the case in eShopOnContainers.

Hope this helps.
