### ISSUE TITLE
Authorization Issue: Basket.API to Identity.API

### ISSUE THREAD

**Issue by Urgen-Dorjee** [dotnet-architecture/eShopOnContainers#1294] opened 2020-04-08 04:01 UTC
In order to understand underlying technologies, I have been tried to rebuild this project so I get the better understanding of its processes and how it is implemented upon each other, however I have been getting an issue while trying to get the authorization code from Identity.API from Basket.API project. Moreover, Identity.API itself having an issue with css file. The css classes defined in Identity.API cshtml files were not there in the site.css file. Therefore home page won't align/display correctly. I don't understand why Identity.API localhost port and Basket.API reference port to Identity.API are different:-    

Basket.API- appsettings.json https://github.com/dotnet-architecture/eShopOnContainers/blob/c948bee89104b6fc903ceb3cee08caf879449c3e/src/Services/Basket/Basket.API/appsettings.Development.json#L13

Identity.API hosting port:  launchSettings https://github.com/dotnet-architecture/eShopOnContainers/blob/c948bee89104b6fc903ceb3cee08caf879449c3e/src/Services/Identity/Identity.API/Properties/launchSettings.json#L14

Error snipped In while try to obtain authorization code:

![image](https://user-images.githubusercontent.com/9157710/78742738-77236200-797a-11ea-8809-4caddd03da5f.png)

Since I have been tried to rebuild this project myself therefore I thought it might be because of that, hence I tried to run your clone project and it has the same issue.

Initially I had tried to search for a related issue, but could not find with an error "unauthorized_client error" but somehow i managed to get to this link going by every issue discussed in the following link:- [Unauthoized_Client Login Error]( https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login)

 Basically, in this thread mostly talked about the docker settings but currently i have not reached to this point, before i get to the docker stuffs I would like to run without containerized and move one step further is my goal. Identity.API which i have rebuild has very much seeded with require client registration in the database therefore it is not problem with client registration, now i have narrow down the issue with redirecturis and i found following ClientRedirectUri registered in Identity.API therefore i tried to debug with VS2019 and an error says "Invalid uri", as I stated above i did not reach to docker stuff therefore how would i make sure that it has correct ClientRedirectUri register with identity.Api to authorize/grant access token. 

Client Registration with Identity.API 
![image](https://user-images.githubusercontent.com/9157710/78748696-48ad8300-798a-11ea-8f49-4d70c8065f66.png)

ClientRedirectUris
![image](https://user-images.githubusercontent.com/9157710/78748770-7266aa00-798a-11ea-9453-75aaa66870bc.png)

Error capture while debugging in VS2019
![image](https://user-images.githubusercontent.com/9157710/78749359-b4442000-798b-11ea-9cb3-a1fa4b26fd3e.png)

Thanks,

**Comment by mvelosop** [comment] 2020-04-09 16:48
Hi @Urgen-Dorjee, Thanks for your feedback.

Please take a look at the [unauthorized_client error on Login](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login) page in the [Frequent errors section](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors) in the [Wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki).

Hope this helps.

**Comment by Urgen-Dorjee** [comment] 2020-04-11 03:50
Greetings! @mvelosop 
   As stated in the previous thread, trust me I already browsed through [this](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login) link but could not get hold of it, as it is mainly talked about the docker-compose file configurations, I will explore containerize and platform orchestration process later down the line, but right now I would like to get into bare minimum stuffs and move forward, so I get the right traction how these technologies has been implemented and how process work in micro-services world.  I would appreciate if you could help me to point in which i would have to look into get this working.   
  Thanks for your time and patience, I have been learning these technologies therefore please bare with me.

**Comment by mvelosop** [comment] 2020-04-14 12:19
Hi @Urgen-Dorjee,

Keep in mind that this app is designed and configured to work in containers so it'll require some configuration work to get it running as independent projects

Anyway you'll need to run some infrastructure containers, like Redis, Mongo and RabbitMQ. You could install them directly in you dev machine, but with Docker it's way easier.

You'll have to configure the `appsettings.json` with the equivalent values from `docker-compose.override.yml`.

As for the specific auth issue, keep in mind that, the client registrations in Identity.API are taken from the configuration values and it's done only during startup.

To make configuration easier, I'd suggest that you run the services only with Kestrel, without using IIS.

Hope this helps.

**Comment by Urgen-Dorjee** [comment] 2020-04-14 13:04
Hello @mvelosop 
   Thanks for the suggestions, however I already setup Redis and RabbitMQ pretty much locally and they have been working fine without any problem, however it is the identity server which could not get the valid redirecturi is the problem and Identity server is configured with SQL Server, which is also installed locally, therefore I can say it does not seems to be problem with infrastructure rather something to do with seeding the identity data with redirecturi, correct if I am wrong. Therefore I would like to know, how to seed correct (redirecturi).

   I have been tried to figure it out.

Thanks,

**Comment by mvelosop** [comment] 2020-04-14 13:41
@Urgen-Dorjee, the [Identity Server section](https://github.com/dotnet-architecture/eShopOnContainers/wiki/unauthorized_client-error-on-login#identity-server) in the "**unauthorized_client error on Login**" wiki page, explains the cause.

If you update the `ClientRedirectUris` table to the actual `rediect_uri` that you get when logging in, for the client (MVC or SPA) you're using, it should work.

**Comment by Urgen-Dorjee** [comment] 2020-04-15 05:09
I am pretty curious to know, since this project is designed for microservices and micro-service means every project is independent in nature, correct me if i am wrong! therefore let's supposed I wanna token from the identity server to access my basket, which is one of backend services. How do I achieve this through swaggerUI feature [Authorize] without having any client involvement like(MVC & SPA). I did not start using any clients UI as of now, it may work as per docker configurations as you pointed in the previous thread. 

  Anyway, thanks for your help. I will try my best to get it going, let's how do I achieve this by understanding every bit and pieces of these projects. I will seek your help, if needed.

**Comment by sughosneo** [comment] 2020-08-12 17:14
Hello Everyone, I see the original question has already been addressed. So I am closing this issue as of now. Please feel free to reopen it, if needed.

Thank you.

**Closed by sughosneo** 2020-08-12 17:14 UTC
