### ISSUE TITLE
[Feature/Improvement] Xamarin.Forms app to include Resilient Http Communication with Polly

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopOnContainers#557] opened 2018-03-23 20:43 UTC
We should consider updating the Http communication from the Xamarin app so it uses resilient approaches like Retries with exponential backoff and circuit breakers.
In the MVC app we’re using Polly for that and a wrapper library that simplifies its usage.

Polly targets .NET 4.0, .NET 4.5 and .NET Standard 1.1 (coverage: .NET Core, Mono, Xamarin.iOS, Xamarin.Android, UWP, WP8.1+), so it supports Xamarin.

**Comment by davidbritch** [comment] 2018-03-29 12:48
Closing as duplicate of #206

**Closed by davidbritch** 2018-03-29 12:48 UTC
Labels: Feature, enhancement
