### ISSUE TITLE
IntegrationEventsScenarios and MarketingScenarios Unit Tests fail due to missing call to app.UseAuthorization()

### ISSUE THREAD

**Issue by InstanceFactory** [dotnet-architecture/eShopOnContainers#1404] opened 2020-08-17 16:23 UTC
Running the unit test cases `IntegrationEventsScenarios.Post_update_product_price_and_catalog_and_basket_list_modified` and `MarketingScenarios.Set_new_user_location_and_get_location_campaign_by_user_id` on my Windows 10 dev machine, both failed with the same error (after local fix of #1403):<br/>
```
Message: 
    System.InvalidOperationException : Endpoint Microsoft.eShopOnContainers.Services.Basket.API.Controllers.BasketController.UpdateBasketAsync (Basket.API) contains authorization metadata, but a middleware was not found that supports authorization.
    Configure your application startup by adding app.UseAuthorization() inside the call to Configure(..) in the application startup code. The call to app.UseAuthorization() must appear between app.UseRouting() and app.UseEndpoints(...).
  Stack Trace: 
    EndpointMiddleware.ThrowMissingAuthMiddlewareException(Endpoint endpoint)
    EndpointMiddleware.Invoke(HttpContext httpContext)
    StaticFileMiddleware.Invoke(HttpContext context)
    AutoAuthorizeMiddleware.Invoke(HttpContext httpContext) line 30
    SwaggerUIMiddleware.Invoke(HttpContext httpContext)
    SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
    <<SendAsync>g__RunRequestAsync|0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
    IntegrationEventsScenarios.Post_update_product_price_and_catalog_and_basket_list_modified() line 37
    --- End of stack trace from previous location where exception was thrown ---
```
Looking at the code I noticed that a call to `app.UseAuthorization()` was not implemented by the three test service startup classes `BasketTestsStartup, LocationsTestsStartup`, and `MarketingTestsStartup` in the overloaded method `ConfigureAuth` in case the configuration item `isTest` is set to `true`.<br/>
After adding this call, both test cases passed, and none of the other test cases were impacted.<br/>
I suggest to add the missing call mentioned above. If you agree, I offer to create the corresponding PR.<br/>
Kind Regards,<br/>
Stefan

**Comment by sughosneo** [comment] 2020-08-20 06:41
Hi Stefan, thanks for submitting this PR. Will test and update.

**Comment by InstanceFactory** [comment] 2020-08-20 10:43
Hi @sughosneo,

Thanks. I will put the fix for this issue and #1403 into the same PR, as the fix for this issue requires the fix of it.

**Comment by sughosneo** [comment] 2020-08-25 07:38
Hi Stefan, thank you for pointing out the issues in functional test cases. 

Now, while testing the PR #1406 (fixes #1403 and #1404) I notice that though it doesn't have the Authorization issue anymore but it fails with following Assert.Equal(). 

![image](https://user-images.githubusercontent.com/13281246/91144973-6463bc80-e6d2-11ea-8e51-96410cd319f6.png)

And that could be because of `var itemUpdated = await GetUpdatedBasketItem(` doesn't update the latest price. And that's the reason the assertion is failing with following check. 

![image](https://user-images.githubusercontent.com/13281246/91145101-9543f180-e6d2-11ea-8ff4-d39a37053074.png)

Are you able to reproduce the same ? Could you please check and update the PR ?

Also, please note, IntegrationEvent for marketing scenario looks good. 

![image](https://user-images.githubusercontent.com/13281246/91146132-18b21280-e6d4-11ea-96c8-bd91b794558b.png)

Thank you again.

**Comment by InstanceFactory** [comment] 2020-08-25 14:35
> 
> 
> Hi Stefan, thank you for pointing out the issues in functional test cases.
> 
> Now, while testing the PR #1406 (fixes #1403 and #1404) I notice that though it doesn't have the Authorization issue anymore but it fails with following Assert.Equal().
> 
> ![image](https://user-images.githubusercontent.com/13281246/91144973-6463bc80-e6d2-11ea-8e51-96410cd319f6.png)
> 
> And that could be because of `var itemUpdated = await GetUpdatedBasketItem(` doesn't update the latest price. And that's the reason the assertion is failing with following check.
> 
> ![image](https://user-images.githubusercontent.com/13281246/91145101-9543f180-e6d2-11ea-8ff4-d39a37053074.png)
> 
> Are you able to reproduce the same ? Could you please check and update the PR ?
>

Hi Sumit,

Sorry, I am not able to reproduce it. Took the latest code via GitHub Desktop, implemented the changes of the PR, started the app (docker-compose build / up), and everything worked fine.

![1404_both_tests_passed](https://user-images.githubusercontent.com/6959462/91186812-c4b52700-e6ef-11ea-923c-fb7a7af9638c.png)

This is the latest part of the dev branch history on my machine:

![1404_status_branches](https://user-images.githubusercontent.com/6959462/91187599-a00d7f00-e6f0-11ea-941d-9ae1fd957332.png)

Am I missing another PR / branch?

**Comment by sughosneo** [comment] 2020-08-26 14:36
Hi Stefan, yes the changes seems to be working fine. 

It was actually failing in one of the environment, where `ProductPriceChangedIntegrationEvent` wasn't getting handled by the handler in `Basket.API`
So the price of the Basket items were not getting updated properly.Hence both of the following assertions were failing under `Post_update_product_price_and_catalog_and_basket_list_modified` test method

```C#
Assert.Equal(newPrice, itemUpdated.UnitPrice);
Assert.Equal(oldPrice, itemUpdated.OldUnitPrice);
```

But when I tested the PR #1406 in newly created Windows VM environment. Everything seems to be working fine. So accepting these changes. 

Thank you for the details and PR

**Comment by sughosneo** [comment] 2020-08-26 14:37
Closing this issue.

**Closed by sughosneo** 2020-08-26 14:37 UTC
Labels: bug

**Comment by InstanceFactory** [comment] 2020-08-26 16:00
> 
> 
> Hi Stefan, yes the changes seem to be working fine.
> 
> ...
> 
> But when I tested the PR #1406 in newly created Windows VM environment. Everything seems to be working fine. So accepting these changes.
> 
> Thank you for the details and PR

Hi Sumit,

Good to hear that it seems to work - hope it will remain this way ;-)

Thanks for the feedback and merging the PR.

Regards,

Stefan
