### ISSUE TITLE
* Exception when signin

### ISSUE THREAD

**Issue by dohuyphuong** [dotnet-architecture/eShopOnContainers#513] opened 2018-02-13 05:53 UTC
Open URL: http://localhost:5100/Account/SignIn
I got an error
```
An unhandled exception occurred while processing the request.
TaskCanceledException: A task was canceled.
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

IOException: IDX10804: Unable to retrieve document from: 'http://10.0.75.1:5105/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()

InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://10.0.75.1:5105/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.ConfigurationManager+<GetConfigurationAsync>d__24.MoveNext()
```

**Comment by eiximenis** [comment] 2018-02-13 08:18
This is usually caused by a firewall.
If works deactivating the firewall try opening the ports as documented in https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)

**Comment by dohuyphuong** [comment] 2018-02-13 08:52
That ports have opened. but it not works. Thanks for your support

![image](https://user-images.githubusercontent.com/36431371/36140875-6a9830d4-10d5-11e8-89d9-7499f03a9029.png)

**Comment by eiximenis** [comment] 2018-02-13 09:25
Some options more...
Try if setting windows firewall **to not** protect DockerNAT works for you (use your neeeded profile):

![image](https://user-images.githubusercontent.com/5191049/36141845-8fa45666-10a6-11e8-9be0-0ec82747b445.png)

Hope this helps!

**Comment by dohuyphuong** [comment] 2018-02-13 09:58
Thank you @eiximenis  
But my machine cannot change this config. that is stupid.

![image](https://user-images.githubusercontent.com/36431371/36143852-d5a259aa-10de-11e8-9a9d-6d66514af44d.png)

**Comment by warappa** [comment] 2018-02-18 09:36
This hit me as well. Should be part of "02. Setting eShopOnContainers in a Visual Studio 2017 environment" where the filewall settings are described.

**Comment by CESARDELATORRE** [comment] 2018-02-19 18:33
@dohuyphuong It could be due to Domain policies from your company?
Your sreeshot says “Some settings are controlled by Group Policy”.
Can you check the same config in a different machine which is not in the enterprise Windows Domain?
If so, Please, try in a machine that is not within an enterprise domain with policies restricting. 
Policies can impact further issues in Docker, as well.

**Comment by CESARDELATORRE** [comment] 2018-02-20 17:35
Closing this issue as it looks it is due to a local PC configuration not being able to open the required ports in the firewall, as specified at the Wiki post for setup:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment

Feel free to open it again if it is due to a different issue.
Thanks,

**Closed by CESARDELATORRE** 2018-02-20 17:35 UTC

**Comment by rafsanulhasan** [comment] 2018-08-11 17:56
-1

**Comment by yuriy-hanzha** [comment] 2019-01-30 13:12
> Thank you @eiximenis
> But my machine cannot change this config. that is stupid.
> 
> ![image](https://user-images.githubusercontent.com/36431371/36143852-d5a259aa-10de-11e8-9a9d-6d66514af44d.png)

@dohuyphuong, seems to be quite late, but try to change Protected Network Connections in Public Profile, not in Domain one.
