### ISSUE TITLE
Bug: Deserialization of a Event does not set the Id correctly

### ISSUE THREAD

**Issue by Eneuman** [dotnet-architecture/eShopOnContainers#837] opened 2018-10-31 21:01 UTC
The event you receive in a EventHandler have a different "Id" and "CreationDate" value then the event you actualy created.

This is because the "Id" and "CreationDate" is readonly so the deserializer cannot set them.

see https://github.com/dotnet-architecture/eShopOnContainers/blob/70332aeeb1994cccc7a44f1e7fe83ef5143d6c00/src/BuildingBlocks/EventBus/EventBus/Events/IntegrationEvent.cs#L13

Shouldn't theese have a "set" aswell?

**Comment by mvelosop** [comment] 2018-12-19 20:38
Hi @Eneuman,

Yes this is a bug, and there's a solution as you can see in issue #667.

I've tested the solution in several projects already so I can confirm it works.

I'm closing this issue now as a duplicate of #667

Thanks.

**Closed by mvelosop** 2018-12-19 20:38 UTC
