### ISSUE TITLE
linux K8s setup seems to be out of date

### ISSUE THREAD

**Issue by dbones** [dotnet-architecture/eShopOnContainers#1130] opened 2019-08-26 17:48 UTC
Hi 

I have been trying (still have an issue with the images) to get the application running on linux based K8s.

(I may have miss understood some of the setup) however the sample seems to be out of sync

* all the gateways have health checks for the underlying services, the urls (configmap entries) need to be added to the deployments (without these the process complains about a missing url)
* the nginx setup may need the annotation: _nginx.ingress.kubernetes.io/ssl-redirect: "false"_

deploy.sh seems to be behind the deploy.ps1 (not in sync)

* does not create the same urls configmap as the deploy.ps1
* makes reference to a frontend.yaml, i cannot find it (unless its generated)
* cannot see a reference for deploying ocelot, for the json files are copied into the configmaps

im looking into why the images are not working.

**Comment by mvelosop** [comment] 2019-08-29 10:36
Hi @dbones, 

I haven't tried the Linux deployment, anyway, are you using the latest **dev** commit?

Hope this helps.

cc/ @eiximenis

**Comment by eiximenis** [comment] 2019-08-30 06:52
Hi!
Please use `/k8s/helm/deploy-all.sh` to deploy using Linux. File `/k8s/deploy.sh` is outdated and will be removed in the near future.
Sorry for the confusion.

If you find any issue with `/k8s/helm/deploy-all.sh` report in this issue, because this file **should work**. If deploy goes OK, feel free to close the issue :)

Please note, that Helm is used to deploy eShopOnContainers right now.

@mvelosop We should take a look at doc/wiki to ensure that are no references to the old `/k8s/deploy`  folder!

Sorry for the confusion!

**Comment by dbones** [comment] 2019-09-02 12:36
@ both, thanks for looking into this, I will move onto the helm charts.

@eiximenis please consider keeping the deployment files, they are a great way to learning K8s without helm charts being added to the mix. (even tho helm charts are the recommended route)

**Comment by aaronwjha** [comment] 2019-09-10 23:58
The wiki seems to have outdated instructions for `/k8s/helm/deploy-all.sh`. At least the script param names are not accurate.

**Comment by RobSteele** [comment] 2020-01-27 20:08
I'm getting the same error with the deploy all script:
**_Begin eShopOnContainers installation using Helm
Installing infrastructure: sql-data
Error: unknown flag: --name
Installing infrastructure: nosql-data
Error: unknown flag: --name
Installing infrastructure: rabbitmq
Error: unknown flag: --name
Installing infrastructure: keystore-data
Error: unknown flag: --name
Installing infrastructure: basket-data
Error: unknown flag: --name
Installing: eshop-common
Installing: basket-api_**

**Comment by RobSteele** [comment] 2020-01-27 20:18
I went ahead and simply removed both instances of "--name" from `/k8s/helm/deploy-all.sh` and it appears that the script ran without error... verifying any problems now

**Comment by Osirisoo0O** [comment] 2020-02-19 03:53
> I'm getting the same error with the deploy all script:
> **_Begin eShopOnContainers installation using Helm Installing infrastructure: sql-data Error: unknown flag: --name Installing infrastructure: nosql-data Error: unknown flag: --name Installing infrastructure: rabbitmq Error: unknown flag: --name Installing infrastructure: keystore-data Error: unknown flag: --name Installing infrastructure: basket-data Error: unknown flag: --name Installing: eshop-common Installing: basket-api_**

Check the Helm Version，Maybe new version is not supported.

**Comment by Luthor36** [comment] 2020-03-12 17:39
> > I'm getting the same error with the deploy all script:
> > **_Begin eShopOnContainers installation using Helm Installing infrastructure: sql-data Error: unknown flag: --name Installing infrastructure: nosql-data Error: unknown flag: --name Installing infrastructure: rabbitmq Error: unknown flag: --name Installing infrastructure: keystore-data Error: unknown flag: --name Installing infrastructure: basket-data Error: unknown flag: --name Installing: eshop-common Installing: basket-api_**
> 
> Check the Helm Version，Maybe new version is not supported.

I think you might be right.  I'm going to downgrade my version of Helm and see if that corrects the issue.  Any idea what the expected Helm version was for this implementation?

**Comment by Luthor36** [comment] 2020-03-12 17:40
> I went ahead and simply removed both instances of "--name" from `/k8s/helm/deploy-all.sh` and it appears that the script ran without error... verifying any problems now

Did this work or were there complications?

**Comment by Luthor36** [comment] 2020-03-12 22:18
FYI.

This seemed to work for Mac.  It seemed to be an issue with a lower version of Helm, but an up-to-date version of Tiller.  I'll update if I discover any issues.

## Downgrade Helm:

### Get Raw Commit Hash

Go to https://github.com/Homebrew/homebrew-core/search?q=kubernetes-helm&type=Commits

Click the Commit Hash button (Like below):

![image](https://user-images.githubusercontent.com/5376529/76567481-db86fa80-647c-11ea-8e1b-d86c01f06f5a.png)

Click **View File**:

![image](https://user-images.githubusercontent.com/5376529/76567536-f48fab80-647c-11ea-8238-73cf747b9bb9.png)

Click **Raw**:

![image](https://user-images.githubusercontent.com/5376529/76567559-040ef480-647d-11ea-8648-724ec6f8312b.png)

Copy the URL, we will need it later:

![image](https://user-images.githubusercontent.com/5376529/76567591-1db03c00-647d-11ea-8f26-9aa90852b656.png)

Ex. https://raw.githubusercontent.com/Homebrew/homebrew-core/1f744b70b9a048d29efa59f8d6a9a2131530b908/Formula/kubernetes-helm.rb

### Unlink Current Helm

`brew unlink helm`

### Install older Helm version

`brew install _raw_url`_

This uses the URL we got from the **Raw** page earlier.

![image](https://user-images.githubusercontent.com/5376529/76567858-a202bf00-647d-11ea-92e7-6889608a995f.png)
![image](https://user-images.githubusercontent.com/5376529/76567865-a7f8a000-647d-11ea-9186-eb374db210de.png)

### Switch to old version of Helm

`brew switch kubernetes-helm _version`_

Use the version that you got the Raw URL from - in this format #.##.# (Example: 2.14.2)

![image](https://user-images.githubusercontent.com/5376529/76568017-032a9280-647e-11ea-9313-e106f75c8068.png)

### Start Helm + Add Tiller

`helm init`

![image](https://user-images.githubusercontent.com/5376529/76568153-44bb3d80-647e-11ea-99e4-f7846d04fc1f.png)


This will update us to the old version of Helm & Tiller, see below:

![image](https://user-images.githubusercontent.com/5376529/76568169-497ff180-647e-11ea-9a0c-2bfcaa96c70e.png)

Now we are downgraded.

The problem is, that I get new issues:

```
Error: release eshop-sql-data failed: namespaces "eshop" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "namespaces" in API group "" in the namespace "eshop"
```

It doesn't seem to be able to get the namespace.

## Tiller Upgrade

Run the following commands:

`kubectl --namespace kube-system create serviceaccount tiller`
`kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller`
`helm init --service-account tiller --upgrade`
  
## Success!

Once I did this, it seemed to work correctly - things installed as they should:

![image](https://user-images.githubusercontent.com/5376529/76568586-230e8600-647f-11ea-9b8a-33db2287131d.png)

If you run `kubectl get pods -n kube-system` - you will see all of the pods:

![Screen Shot 2020-03-12 at 4 40 16 PM](https://user-images.githubusercontent.com/5376529/76571373-57854080-6485-11ea-9a2c-0a783c726fb9.png)

**Comment by sughosneo** [comment] 2020-07-28 13:25
Hi @dbones,  we have recently updated our scripts to support helm 3.x and k8s 1.16. 
Here is the link of the [wiki page](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Local-Kubernetes)

In case if you want to give it a try. 

Thanks.

**Comment by sughosneo** [comment] 2020-08-05 11:33
Hi @dbones , we are closing this issue as of now. If you face any further challenges please feel free to write back and reopen it. 

Thank you.

**Closed by sughosneo** 2020-08-05 11:33 UTC
Labels: kubernetes
