### ISSUE TITLE
Unable to login - getting error

### ISSUE THREAD

**Issue by MohammadShoeb-cmd** [dotnet-architecture/eShopOnContainers#1478] opened 2020-09-26 13:50 UTC
Hi, thanks for this great project, I have followed all the steps mentioned to set up this project

1. Updated identity DB as mentioned in one of the query reply
![image](https://user-images.githubusercontent.com/65648405/94342223-36ed9400-002d-11eb-8f6f-24c25c43ee9f.png)

2. Login with default user name and password given
User: demouser@microsoft.com
Password: Pass@word1

3. however getting below error 
![image](https://user-images.githubusercontent.com/65648405/94342235-52f13580-002d-11eb-8083-83acf97dfc15.png)

Could you please guide and assist me on this, as I am struck at this moment and unable to move forward to explore and debug this application

**Comment by sughosneo** [comment] 2020-09-28 04:36
Hi @MohammadShoeb-cmd , thank you for your feedback. 

You may want to refer our wiki page - [Login page - Exception: Correlation failed](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Frequent-errors#login-page---exception-correlation-failed)

This issue is duplicate of https://github.com/dotnet-architecture/eShopOnContainers/issues/1391

Hope this helps !

**Comment by sughosneo** [comment] 2020-09-30 05:17
Hi @MohammadShoeb-cmd , I am closing this issue considering it as a duplicate of #1391 . If you have any further questions, please feel free to reopen it. 

Thank you.

**Closed by sughosneo** 2020-09-30 05:17 UTC
Labels: docker-compose
