### ISSUE TITLE
The type 'RazorViewAttribute' exists in both 'Microsoft.AspNetCore.Mvc.Razor

### ISSUE THREAD

**Issue by Arpanx** [dotnet-architecture/eShopOnContainers#644] opened 2018-06-22 17:19 UTC
For 2 days I did everything according to the instructions, the project was compiled. But here's the error at the start of the MVC application
Win10, 8 GB
![777](https://user-images.githubusercontent.com/15828141/41789744-04eb4430-7659-11e8-9e5e-3e53dd135665.png)

**Comment by Arpanx** [comment] 2018-06-23 04:35
changed the brunch to "master", copied it into VS2017 launched, the first page failed to open the HTML page (Internal Error), but waited for minutes and did F5 and everything works as it should!
It's hard to run on 8 GB Core I7-100 and slow internet. 5 days compiled differently, and all the time something did not work. That Order service did not work.
Now thank God everything works. Great project!

**Comment by mvelosop** [comment] 2018-06-23 18:49
Hi @Arpanx,

Great you could finally get it running! When working with such a low memory configuration, it's better if you run it from the CLI as explained here: https://github.com/dotnet-architecture/eShopOnContainers/wiki/03.-Setting-the-eShopOnContainers-solution-up-in-a-Windows-CLI-environment-(dotnet-CLI,-Docker-CLI-and-VS-Code)

As for the error it's already been logged as #600.

Hey and thanks for the comment 👍

Closing this issue as duplicate of #600.

**Closed by mvelosop** 2018-06-23 18:49 UTC
