### ISSUE TITLE
system.digonist tool 4.3.0 is not compatatble with netcore 1.1 iissue while buidling  in vs2017community

### ISSUE THREAD

**Issue by babula38** [dotnet-architecture/eShopOnContainers#165] opened 2017-04-13 16:08 UTC
clone the project from github try to load the solution got this error window.

"system.digonist tool 4.3.0 is not compatatble with netcore 1.1 iissue while buidling  in vs2017community"

**Comment by CESARDELATORRE** [comment] 2017-04-18 20:38
We're not able to reproduce this issue. Is it still happening to you? - could you try with a different machine/environment?

**Comment by SychevIgor** [comment] 2017-06-22 11:31
@babula38 do you still have this issue?

**Comment by SychevIgor** [comment] 2017-09-07 15:41
@CESARDELATORRE I guess we can close this issue, since we have no answer from @babula38

**Comment by CESARDELATORRE** [comment] 2017-09-07 15:45
Closing this.

**Closed by CESARDELATORRE** 2017-09-07 15:45 UTC
