### ISSUE TITLE
Questions about PR

### ISSUE THREAD

**Issue by rafsanulhasan** [dotnet-architecture/eShopOnContainers#756] opened 2018-09-07 04:04 UTC
Hi eShopOnContainers team,

I have created some PRs bit didn't get any response. I've closed some PRs (#738, #740, #742) and Issues that are no longer valid or I have made them a mess due to pushing commits incorrectly. Prior to that, I didn't know how it works. Sorry for spamming. What I'm writing this issue for is to be ensured about my PRs are submitted correctly? If they worth reviewing please let me know. If they still seem to be too messy, please give suggest me how can I improve those. 
Look forward to hearing from you.
And again, I really appreciate your initiatives to show the sample open-sourced and with this repo, we devs not only are learning deign/programming, but also learning how to do teamworks through source-control systems. 
Thanks in advance for your effort to teach me how to commit or how to create a good PR that is easy to review. Is there any standardized way of doing this?

**Comment by rafsanulhasan** [comment] 2018-09-13 19:36
@CESARDELATORRE @mvelosop @ardalis

**Comment by CESARDELATORRE** [comment] 2018-09-13 21:08
@rafsanulhasan - We've been focusing on other duties in the last days. I hope pretty soon we'll be able to focus on these PRs while updating eShopOnContainers during the upcoming weeks, ok?

I prefer to take our time reviewing the PRs because if PRs are merged without proper testing, they can cause significant regression issues, as sometimes it happened..

We really appreciate your PRs and all of them will be taken into account.
👍 Thanks.

**Comment by CESARDELATORRE** [comment] 2018-09-13 21:09
Closing this issue, as it's been answered. :)

**Closed by CESARDELATORRE** 2018-09-13 21:09 UTC

**Comment by rafsanulhasan** [comment] 2018-09-13 21:12
Thanks
