### ISSUE TITLE
The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by kingreatwill** [dotnet-architecture/eShopOnContainers#418] opened 2017-12-02 06:33 UTC
![image](https://user-images.githubusercontent.com/13087689/33512549-96b72676-d76d-11e7-9a93-9478582908d6.png)

**Comment by tuyen-vuduc** [comment] 2017-12-02 11:00
Same issue here. I did expect the app must have been runnable without Azure.

**Comment by eiximenis** [comment] 2017-12-02 11:48
Hi,
That is just a docker warning. This variable is not needed for running application locally.

Which issue are you experiencing??? Azure is definitely not needed to run the app!

**Comment by ptk86** [comment] 2017-12-02 20:46
Same issue here.

**Comment by CESARDELATORRE** [comment] 2017-12-02 21:18
Those warnings about Environment variables for Azure are just warnings when you are not using it. You don’t need Azure in order to run the application in Docker.
If it is not working for you it has to be related to a different issue, probably a Docker environmentalists issue. Do you have any additional error after the warnings about the Azure environment variables?

**Comment by tuyen-vuduc** [comment] 2017-12-03 04:49
After reading very carefully the build output, I found these lines

```
ERROR: for dockercompose1690267491427237613_webstatus_1  Cannot start service webstatus: Mounts denied: 
The path /usr/local/share/dotnet/sdk/NuGetFallbackFolder
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

That's the root cause for my issue. I could run up Docker instances on my Mac.

**Comment by CESARDELATORRE** [comment] 2017-12-03 19:59
Closing this issue. This issue was not related to Azure environment variables, which are just optional.

**Closed by CESARDELATORRE** 2017-12-03 19:59 UTC
