### ISSUE TITLE
Multiple integration event handlers per event not firing

### ISSUE THREAD

**Issue by ADringer** [dotnet-architecture/eShopOnContainers#900] opened 2019-01-09 21:56 UTC
Hi,

Using the BuildingBlocks Event Bus code, I've got a an integration event: `NameChangedIntegrationEvent`.

I then have two handlers for this:

`public class NameChangedFooIntegrationEventHandler : IIntegrationEventHandler<NameChangedIntegrationEvent>`

`public class NameChangedBarIntegrationEventHandler : IIntegrationEventHandler<NameChangedIntegrationEvent>`

And then registered as such:

eventBus.Subscribe<NameChangedIntegrationEvent, IIntegrationEventHandler<NameChangedIntegrationEvent>>();

In the BuildingBlocks code I see the following:

```
var subscriptions = _subsManager.GetHandlersForEvent(eventName);
                    foreach (var subscription in subscriptions)
                    {
                    ...
                    }
```

So assumed that it would be able to process the two event handlers but the subscription manager only returns one handler. 

Should this return all handlers for a specific event?

**Comment by mvelosop** [comment] 2019-01-10 19:55
Hi @ADringer,

I've just been checking the code at several points and it looks like the InMemoryEventBusSubcriptionManager correctly handles multiple subscribers per event.

Are you sure all expected handlers have been subscribed to the event by the time you have checked?

Is this something happening in eShopOnContainers that you can reproduce?

**Comment by ADringer** [comment] 2019-01-11 09:05
Hi, @mvelosop,

I think you're right, the `InMemoryEventBusSubcriptionManager` does handle multiple subscriptions fine, I think it's just how the subscriptions are set up.

In the OrdersApi the subscription is added as:

`eventBus.Subscribe<GracePeriodConfirmedIntegrationEvent, IIntegrationEventHandler<GracePeriodConfirmedIntegrationEvent>>();`

So this adds just the one handler for the event (although no concrete implementation). It then uses AutoFac to resolve the handler (`IIntegrationEventHandler<GracePeriodConfirmedIntegrationEvent>`) which I assume just gets the first one.

I believe (although haven't had a chance to try) that each subscription handler needs to be registered itself e.g:

```
eventBus.Subscribe<GracePeriodConfirmedIntegrationEvent, GracePeriodConfirmedIntegrationEventHandler>();
eventBus.Subscribe<GracePeriodConfirmedIntegrationEvent, MyOtherIntegrationEventHandler>();
```

**Comment by mvelosop** [comment] 2019-01-11 10:52
That's probably be the best (simplest) option for the time being.

It could also be implemented by resolving an `IEnumerable<TH>`  when getting the event handlers.

https://github.com/dotnet-architecture/eShopOnContainers/blob/a8b705fcc60008ba553b993158e8626284a6f8fb/src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs#L217-L232

It **should** work without too much hassle, but I think it's definitely easier, and safer, to register concrete handlers.

Thinking it over, I'd prefer the concrete registration, because I can imagine horrible debugging scenarios otherwise!

Hope this helps!

**Comment by mvelosop** [comment] 2019-02-08 18:14
Closing as it doesn't affect eShopOnContainers now.

**Closed by mvelosop** 2019-02-08 18:14 UTC
