### ISSUE TITLE
can not show login page  on mvc site 

### ISSUE THREAD

**Issue by infofromca** [dotnet-architecture/eShopOnContainers#295] opened 2017-08-26 19:08 UTC
just click log in ,  go to http://localhost:5100/Account/SignIn, then get this 
![login-err](https://user-images.githubusercontent.com/297675/29744297-4c3c357c-8a70-11e7-97e0-f67eed06ca8e.png)

**Comment by CESARDELATORRE** [comment] 2017-08-26 19:51
@infofromca Things to try:
1. Did you open the firewall ports as specified in the setup intructions?: Se section about the firewall rules. You can do it manually or running the PowerShell Script:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/02.-Setting-eShopOnContainers-in-a-Visual-Studio-2017-environment 

2. Is the Identity.API project container up and running when you do a "docker ps" from command line?

**Comment by CESARDELATORRE** [comment] 2017-08-31 03:59
Also, try deleting all the old Docker images from eShopOnContainers registered in your local Docker and re-deploy.
You can do it by running this PowerShell Script:
https://github.com/dotnet-architecture/eShopOnContainers/blob/netcore2/cli-windows/delete-vs-and-eshop-images.ps1
It might be because any older Docker image was not updated.

**Comment by buzzfrog** [comment] 2017-09-06 12:31
I have the same problem. I'm on branch netcore2. I have done both things that you mentioned above. Image identity.api:dev is up and running.

**Comment by CESARDELATORRE** [comment] 2017-09-07 05:23
The DEV branch is already NET Core 2. A brand-new for clone should work for you. Make sure you delete older images, just in case.

**Comment by CESARDELATORRE** [comment] 2017-09-07 05:23
The DEV branch is already NET Core 2. A brand-new git clone should work for you. Make sure you delete older images, just in case.

**Comment by huangmaoyixxx** [comment] 2017-09-08 01:24
I have same problem and  solved it  by reading followed text in the question area

eventually, +1 VS2017 on Win10, Docker 17.06.1:After the first compile and startup, I was struggling for a while with this error (also mentioned a few times before, but with no apparent solution):IDX10803: Unable to obtain configuration from: 'http://10.0.75.1:5105/.well-known/openid-configuration'.Investigating this, I found that the request for this address worked from a local browser, but not from another container. Looking into the firewall rules of the ps-script gave no results, but disabling the vpnkit block rules (probably installed by Docker CE) solved the problem!(I am not quite sure if the rules applied by this project was intended to fix this or not, and/or if my system is any different from any default system with Docker CE, but maybe anyone can confirm. Sorry for spamming this topic, but it is apparently the only hit for "IDX10803")EDIT: Just realized how obvious this is: Upon first start-up of the project, you'll get a default firewall-prompt by windows, asking to allow vpnkit to access network resources. If you're in a domain network, the default is to allow for domain network, and to block for public profile. However, from inside the docker containers, the request appears to be on public profile, so these rules will cause some trouble
--

**Comment by buzzfrog** [comment] 2017-09-08 07:13
Great. 
I want to confirm what @huangmaoyixxx wrote above. When I disabled the firewall rule vpnkit for TCP it worked.

**Comment by eiximenis** [comment] 2017-09-08 07:36
Hi! I added a reference to @huangmaoyixxx  comment in the FAQ section, to help other people!

Thanks!

**Comment by CESARDELATORRE** [comment] 2017-09-10 00:15
Closing this issue.

**Closed by CESARDELATORRE** 2017-09-10 00:15 UTC

**Comment by niras-nmr** [comment] 2017-09-20 13:40
Hi!
How did you disable the firewall rule for vpnkit? Or could you help with a link to the FAQ section where a solution to this error is described?

Thanks!

**Comment by buzzfrog** [comment] 2017-09-21 09:13
1. Open Windows Firewall
2. Go to Advanced settings
3. Click on Inbound Rules
4. Find vpnkit and disable rule
(I don't know if it break something else. So be cautious when doing this.)

**Comment by IharHrunt** [comment] 2018-02-01 07:52
I also wish to confirm that it works. Thanks!

**Comment by VoodooSV** [comment] 2018-09-06 10:01
**huangmaoyixxx**
Thanks! It helps me too!

**Comment by mvelosop** [comment] 2019-02-27 13:45
Added a reference here from the setup pages on Windows.

**Comment by zameerh** [comment] 2020-06-07 18:30
Login page error is resolved by a workaround, use docker-compose up and when the services are up navigate to
http://docker.for.win.localhost:5100/ for webmvc and
http://docker.for.win.localhost:5104/ for webspa

**Comment by pavanarya** [comment] 2020-06-26 14:36
I am able to solve the login issue by navigating to login from this
http://docker.for.win.localhost:5100/
