### ISSUE TITLE
Integration Event Repository Async Methods give error.

### ISSUE THREAD

**Issue by cagdassemerciofficial** [dotnet-architecture/eShopOnContainers#668] opened 2018-07-06 11:48 UTC
Hello,

The below integration event code block gives the following error:

Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'TestDBContext'.

But if we use _orderRepository.Get(@event.OrderId) instead of _orderRepository.GetAsync(@event.OrderId), it runs successfully.

Anyone here can explain/solve this?

 ```
public async Task Handle(OrderPaymentFailedIntegrationEvent @event)
{
     var orderToUpdate = await _orderRepository.GetAsync(@event.OrderId);

     orderToUpdate.SetCancelledStatus();

     await _orderRepository.UnitOfWork.SaveEntitiesAsync();
}
```

**Comment by mvelosop** [comment] 2018-08-10 11:48
Hi @cagdassemerciofficial, 

Does this happen in eShopOnContainers? I can't reproduce the error.

**Comment by mvelosop** [comment] 2018-08-22 09:35
Closing this issue as it seems unrelated to eShopOnContainers, will reopen if needed.

**Closed by mvelosop** 2018-08-22 09:35 UTC
